#!/usr/bin/env python3
"""
🌴 MANIFEST BUILDER v1 - GLOBAL HUSTLER EDITION
Generates the master "Cold Start" reference document for any app.
"""
import sys
from pathlib import Path

TEMPLATE = """# ┎━─━─━─━─━─━─━─━─━─━─━─━─━─━─━┒
# 🌴 MISSION MANIFEST: {name}
# ┖━─━─━─━─━─━─━─━─━─━─━─━─━─━─━┚

## 🎯 THE MISSION
{mission}

## 🧠 THE LOGIC (PLAY-BY-PLAY)
{logic}

## 📊 THE SCOREBOARD
{scoreboard}

## 📝 NEXT STRIKES (ROADMAP)
{roadmap}

## 🏛️ ARCHITECTURE DECISIONS (ADRs)
{adrs}

---
*Generated by MY MISSION: Global Hustler Edition*
"""

def build_manifest(root_dir, data):
    root_path = Path(root_dir).resolve()
    content = TEMPLATE.format(
        name=root_path.name.upper(),
        mission=data.get('mission', 'Define the core hustle.'),
        logic=data.get('logic', 'How the data flows.'),
        scoreboard=data.get('scoreboard', '- [ ] Feature 1'),
        roadmap=data.get('roadmap', '1. Strike A'),
        adrs=data.get('adrs', 'Why we built it this way.')
    )
    
    manifest_path = root_path / "MISSION_MANIFEST.md"
    manifest_path.write_text(content)
    return str(manifest_path)

if __name__ == "__main__":
    # This is mainly a helper; the Agent will use the logic directly
    print("Manifest Builder Ready. Standing by for data.")
